### ISSUE TITLE
https://github.com/groonga/meetup/ に移動しませんか？

### ISSUE THREAD

**Issue by kou** [groonga/groonga-document-read-ja#3]
https://github.com/groonga/meetup/ というGroonga関連のイベントの調整をまとめているリポジトリーがあり、イベント毎にIssueをたてて調整しています。もしかしたら、このリポジトリーもそっちに収容してしまった方が協力者が増えたりとかやりやすくなるかもしれません。

ということで、このリポジトリーを https://github.com/groonga/meetup/tree/master/document-read-ja/ 以下とかに移動して、イベント調整も https://github.com/groonga/meetup/ のIssueを使うのはいかがでしょうか？

もし、移動しよう！ということになれば、このリポジトリーの書き込み権限を持っている人に https://github.com/groonga/meetup/ の書き込み権限を設定します。

**Comment by redfigure** [comment]
移動賛成です。
ディレクトリ名のルールが決まればすぐにでもやっていいと思ってます。

**Comment by kou** [comment]
確認ありがとうございます！

@tamano どう思いますか！？

**Comment by tamano** [comment]
@kou いいと思います :+1:

**Comment by kou** [comment]
では、移動しましょう！

ディレクトリーは https://github.com/groonga/meetup/tree/master/document-read-ja/ で問題ありそうですか？なさそうなら、そこに移動してしまってください！

あと、 https://github.com/groonga/meetup/issues に次回ようのissueをたててもらえますか！？

**Comment by tamano** [comment]
@redfigure さんが、新しくIssueを作成してくれました。

https://github.com/groonga/meetup/issues/7

**Comment by kou** [comment]
いえーい！

では、データの移動が完了したらこのリポジトリーは消しますね。

**Comment by tamano** [comment]
データの移動ですが、コミットログまで移動しますか？
もしデータだけで問題なければ、僕の方で実施可能です。

コミットログまで必要でしたら、どなたかお願いいたしたく・・・

**Comment by kou** [comment]
データだけで大丈夫です！お願いします！

**Comment by tamano** [comment]
移動しました。

https://github.com/groonga/meetup/tree/master/document-read-ja/

リポジトリの削除をお願いします。

**Comment by kou** [comment]
ありがとうございます！
削除しておきます！
